// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQntojpAFvUQvk_1Kl9PWrPRdf-7vUAu4',
    appId: '1:617048593807:web:a030e1a81396823752a7fa',
    messagingSenderId: '617048593807',
    projectId: 'smart-home-monitoring-e99e1',
    authDomain: 'smart-home-monitoring-e99e1.firebaseapp.com',
    storageBucket: 'smart-home-monitoring-e99e1.appspot.com',
    measurementId: 'G-23W5MPJ2X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOJZKI-qRe5R4NCXpIVzVb5i8NSAvMs0Y',
    appId: '1:617048593807:android:e1ec9a0cad009b0052a7fa',
    messagingSenderId: '617048593807',
    projectId: 'smart-home-monitoring-e99e1',
    storageBucket: 'smart-home-monitoring-e99e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1CxogSKd68Cg4tgxER1eq3vIsCmYOW-A',
    appId: '1:617048593807:ios:56e2957a63ecc42752a7fa',
    messagingSenderId: '617048593807',
    projectId: 'smart-home-monitoring-e99e1',
    storageBucket: 'smart-home-monitoring-e99e1.appspot.com',
    iosBundleId: 'com.example.assignmentSensor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1CxogSKd68Cg4tgxER1eq3vIsCmYOW-A',
    appId: '1:617048593807:ios:56e2957a63ecc42752a7fa',
    messagingSenderId: '617048593807',
    projectId: 'smart-home-monitoring-e99e1',
    storageBucket: 'smart-home-monitoring-e99e1.appspot.com',
    iosBundleId: 'com.example.assignmentSensor',
  );
}
